# Generated by Django 5.0.6 on 2024-06-11 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Vendedor')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido del Vendedor')),
                ('dni', models.IntegerField(unique=True, verbose_name='DNI del Cliente')),
                ('cuil', models.IntegerField(null=True, unique=True, verbose_name='cuil')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Vendedor')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido del Vendedor')),
                ('dni', models.IntegerField(unique=True, verbose_name='DNI del Cliente')),
                ('legajo', models.IntegerField(unique=True, verbose_name='legajo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateField(auto_now_add=True, verbose_name='Fecha de Entrega')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100, verbose_name='Nombre del Producto')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripcion')),
                ('precio', models.IntegerField(unique=True, verbose_name='precio')),
                ('imagen_url', models.URLField(verbose_name='Imagen_url')),
                ('cliente', models.ManyToManyField(through='web.Pedido', to='web.cliente')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.vendedor')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.producto'),
        ),
    ]
