# Generated by Django 5.0.4 on 2024-06-02 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del cliente')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido del Cliente')),
                ('dni', models.IntegerField(unique=True, verbose_name='DNI del Cliente')),
                ('cliente_id', models.IntegerField(unique=True, verbose_name='ID del cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_id', models.IntegerField(unique=True, verbose_name='ID del cliente')),
                ('fecha_entrega', models.DateField(verbose_name='Fecha de Entrega')),
                ('descripcion_pedido', models.CharField(max_length=200, verbose_name='Descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Vendedor')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido del Vendedor')),
                ('vendedor_id', models.IntegerField(unique=True, verbose_name='ID del Vendedor')),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre del Producto'),
        ),
    ]
