# Generated by Django 5.0.4 on 2024-06-23 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(max_length=100, verbose_name='Apellido :'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dni',
            field=models.IntegerField(unique=True, verbose_name='DNI :'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre :'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_entrega',
            field=models.DateField(verbose_name='Fecha de Entrega'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(max_length=200, verbose_name='descripcion'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen_url',
            field=models.URLField(verbose_name='imagen_url'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre_producto',
            field=models.CharField(max_length=100, verbose_name='nombre_producto'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='apellido',
            field=models.CharField(max_length=100, verbose_name='Apellido :'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='dni',
            field=models.IntegerField(unique=True, verbose_name='DNI :'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre :'),
        ),
    ]
